# Use the README file as a reference to customize settings.

Task:
  fields:
    default: name, description, points, minimum_global_level, time_limit, Category_id, user_story_id
    form: name, description, points, minimum_global_level, time_limit, Category_id, user_story_id
  relationships: 
  application: Application
